spring.application.name=securefileshare
spring.datasource.url=jdbc:mysql://localhost:3306/securefileshare
spring.datasource.username=root
spring.datasource.password=your_own_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false
